### ISSUE TITLE
Hydration failed occurs when manually reloading

### ISSUE THREAD

**Issue by hagishi** [rphlmr/remix-hono-vite#1]
Hello 

Thank you for sample.

```
Hydration failed because the initial UI does not match what was rendered on the server
```

When I ran the sample on my local machine, 
I encountered an issue where 'Hydration failed' occurs and styles are not applied if I manually reload after changing the file.

Does this happen in your environment?

**Comment by rphlmr** [comment]
Thanks for reporting.
I will look at that with a more complex page.

**Comment by rphlmr** [comment]
I can't reproduce :/

**Comment by hagishi** [comment]
Really!! 
Thank you for checking.

**Comment by rphlmr** [comment]
Tell me what is your OS (I'm on macOS).

**Comment by hagishi** [comment]
I'm also using macOS and running it with Bun. :)

**Comment by hagishi** [comment]
@rphlmr 
I will share a screen video.

https://github.com/rphlmr/remix-hono-vite/assets/473379/52d7b728-7d8b-49e3-9282-76b14f73bf37

**Comment by rphlmr** [comment]
@hagishi how is your css imported?

Maybe https://github.com/rphlmr/remix-hono-vite/pull/3 can solves that.

**Comment by rphlmr** [comment]
Tailwind demo since https://github.com/rphlmr/remix-hono-vite/pull/4

**Comment by hagishi** [comment]
@rphlmr 

> how is your css imported?

I imported it in root.tsx

I tried the latest merged template, and it behaved as expected. 
Thank you!!!!!!!!!!!
