### ISSUE TITLE
Hydration failed when using "npm start"

### ISSUE THREAD

**Issue by moeakwak** [rphlmr/remix-hono-vite#10]
Hello,

I've been experimenting with this repository for a while. It runs smoothly in development mode, but crashes in production. The console reports a "Minified React error #418", indicating a "Hydration failed because the server rendered HTML didn't match the client." error. 

**Steps to reproduce:**

```bash
git clone https://github.com/rphlmr/remix-hono-vite
cd remix-hono-vite
pnpm i
pnpm run build
pnpm start
```

**Environment:**

- Node.js v20.11.1
- MacOS on M1 Pro

Upon visiting http://localhost:3000/, the page fails to load properly, displaying several errors in the console:

```
Error: Minified React error #418; visit https://reactjs.org/docs/error-decoder.html?invariant=418 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.

Uncaught Error: Minified React error #423; visit https://reactjs.org/docs/error-decoder.html?invariant=423 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
```

I have tried removing all browser extensions, but this has not resolved the issue.

And I found this issue seems similar to: https://github.com/remix-run/remix/issues/2570

Does this happen in your environment?

Any assistance would be greatly appreciated. Thank you in advance for your help!

**Comment by moeakwak** [comment]
Oh, I figured it out! Finally after several hours of painful research.

Following the advice in this comment: https://github.com/remix-run/remix/issues/9268#issuecomment-2067964520, everything now works normally.

**Comment by rphlmr** [comment]
Oh, thanks for your research!
