### ISSUE TITLE
[vite] hmr invalidate

### ISSUE THREAD

**Issue by rphlmr** [rphlmr/remix-hono-vite#2]
This is a reported bug.
A false positive, everything works fine 😇

**Comment by danestves** [comment]
It's failing for me to do the HMR, sometimes doesn't make the refresh

**Comment by rphlmr** [comment]
Thanks for reporting.

It will be hard to identify if it is hono dev server or remix hmr that is failing.
According to https://discord.com/channels/770287896669978684/1197954326165995662 I guess it is maybe hono dev server.
Anything in particular I can reproduce?
I will try porting remix indie stack to see how it behaves with a real project.

**Comment by rphlmr** [comment]
A demo (Remix indie stack): https://github.com/rphlmr/vite-hono-indie

**Comment by rphlmr** [comment]
Soon fixed by https://github.com/remix-run/remix/pull/8580
